#!/usr/bin/env python3
"""Derive the authoritative ggml_type table from the vendored upstream C sources.

Run:  python3 tools/derive_types.py            # regenerate sentinel/_type_table.py + print
      python3 tools/derive_types.py --check    # fail if committed table is stale

This exists so nobody (human or model) ever *types* a quant block size by
hand. The sizes in this repo come from the static_assert(sizeof(block_X) ==
...) lines and the type_traits table in the vendored ggml-common.h /
ggml.h / ggml.c copies, evaluated against the upstream QK_* constants.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VENDOR = HERE / "vendor"
TARGET = HERE.parent / "sentinel" / "_type_table.py"

FILE_REFS = {
    "ggml.h": "ggml-org/ggml v0.24.0 include/ggml.h",
    "ggml-common.h": "ggml-org/ggml v0.24.0 src/ggml-common.h",
    "gguf.h": "ggml-org/ggml v0.24.0 include/gguf.h",
    "gguf-py_constants.py.reference": "ggml-org/llama.cpp master gguf-py/gguf/constants.py",
}

SZMAP = {
    "ggml_half": 2, "ggml_half2": 4, "ggml_fp16_t": 2, "ggml_bf16_t": 2,
    "uint8_t": 1, "int8_t": 1, "uint16_t": 2, "int16_t": 2,
    "uint32_t": 4, "int32_t": 4, "float": 4, "float32_t": 4, "double": 8,
    "int64_t": 8, "uint64_t": 8,
}


def vendored_digest() -> str:
    h = hashlib.sha256()
    for name in sorted(FILE_REFS):
        h.update(name.encode())
        h.update((VENDOR / name).read_bytes())
    return h.hexdigest()[:16]


def derive():
    ghdr = (VENDOR / "ggml.h").read_text()
    chdr = (VENDOR / "ggml-common.h").read_text()
    # We also need the type_traits table from ggml.c; the vendored copy lives
    # alongside in tools/vendor (fetched from ggml.c at tag v0.24.0).
    gsrc = (VENDOR / "ggml.c").read_text()

    enum = {}
    for line in ghdr.splitlines():
        if line.lstrip().startswith("//"):
            continue
        mm = re.match(r"\s*(GGML_TYPE_\w+)\s*=\s*(-?\d+),?", line)
        if mm and mm.group(1) != "GGML_TYPE_COUNT":
            enum[mm.group(1)] = int(mm.group(2))
    formulas = dict(re.findall(r"static_assert\(sizeof\(block_(\w+)\)\s*==\s*([^,]+),", chdr))
    consts = {k: int(v) for k, v in re.findall(r"#define\s+(QK\w+)\s+(\d+)", chdr)}
    consts["K_SCALE_SIZE"] = int(re.search(r"#define\s+K_SCALE_SIZE\s+(\d+)", chdr).group(1))
    consts["IQ3S_N_SCALE"] = consts["QK_K"] // 64

    m = re.search(
        r"static const struct ggml_type_traits type_traits\[GGML_TYPE_COUNT\] = \{(.*?)\n\};",
        gsrc, re.S,
    )
    if m is None:
        raise SystemExit("type_traits table not found in vendored ggml.c -- re-vendor")
    entries = re.findall(r"\[((?:GGML_TYPE_\w+)|\d+)\]\s*=\s*\{(.*?)\}", m.group(1), re.S)

    def evalf(expr: str) -> int:
        expr = re.sub(r"sizeof\(\s*([\w]+)\s*\)", lambda mm: str(SZMAP[mm.group(1)]), expr)
        return int(eval(expr, {"__builtins__": {}}, dict(consts)))

    table = {}
    for key, ent in entries:
        ev = enum.get(key)
        name = re.search(r'\.type_name\s*=\s*"([^"]*)"', ent).group(1)
        bs = re.search(r"\.blck_size\s*=\s*([^,\n]+),", ent).group(1).strip()
        ts = re.search(r"\.type_size\s*=\s*([^,\n]+),", ent).group(1).strip()
        quant = bool(re.search(r"\.is_quantized\s*=\s*true", ent))
        if bs == "0":
            if ev is not None:
                raise SystemExit(f"removed type id {key} unexpectedly present in enum")
            continue
        blck = int(bs) if bs.isdigit() else evalf(bs)
        mm = re.fullmatch(r"sizeof\(block_(\w+)\)", ts)
        if mm:
            b = mm.group(1)
            candidates = [b, _strip_block_prefix(b)]
            formula = next((formulas[c] for c in candidates if c in formulas), None)
            if formula is None:
                raise SystemExit(f"no static_assert sizeof formula for block_{b}")
            size = evalf(formula)
        else:
            size = evalf(ts)
        if ev is None:
            raise SystemExit(f"type {key} in traits but not in enum -- re-vendor")
        table[ev] = {"id": ev, "enum": key, "name": name, "blck": blck, "size": size, "quant": quant}

    expected = sorted(enum.values())
    got = sorted(table)
    if got != expected:
        missing = set(expected) - set(got)
        extra = set(got) - set(expected)
        raise SystemExit(f"derived table {len(got)} entries != enum {len(expected)} ids; missing={missing} extra={extra}")
    return table


def _strip_block_prefix(b: str) -> str:
    return b[len("block_"):] if b.startswith("block_") else b


HEADER_TEMPLATE = '''"""AUTO-GENERATED by tools/derive_types.py -- DO NOT EDIT BY HAND.

Every block-size here was computed from the static_assert(sizeof(block_X)==...)
lines and the type_traits table in the vendored upstream C sources; regenerate
with ``python3 tools/derive_types.py``. The vendored_digest below is pinned into
a unit test so a vendored-source change without regeneration fails CI.
"""
from __future__ import annotations

DERIVED_FROM = {derived_from_repr}
VENDORED_SHA = {sha!r}

# id -> {{id, enum, name, blck, size, quant}} per ggml.h enum ggml_type (GGML_TYPE_COUNT = 43)
TYPE_TABLE = {table_repr}
'''


def render(table) -> str:
    derived_from = {k: FILE_REFS[k] for k in sorted(FILE_REFS)}
    tbl = {str(ev): table[ev] for ev in sorted(table)}
    return HEADER_TEMPLATE.format(
        derived_from_repr=repr(derived_from),
        sha=vendored_digest(),
        table_repr=repr(tbl),
    )


def main(argv):
    table = derive()
    out = render(table)
    if "--check" in argv:
        current = TARGET.read_text()
        if current != out:
            print("STALE: committed _type_table.py differs from vendored-source derivation.")
            print("Run: python3 tools/derive_types.py")
            return 1
        print("OK: committed table matches vendored sources ({} types).".format(len(table)))
        return 0
    TARGET.write_text(out)
    print(f"wrote {TARGET} ({len(table)} types, digest {vendored_digest()})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
