"""Derive the official GGUF metadata-key registry from the vendored llama.cpp
gguf-py constants file. Key spellings are extracted from upstream, never
hand-typed. Regenerate: python3 tools/derive_keys.py
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VENDOR = HERE / "vendor" / "gguf-py_constants.py.reference"
TARGET = HERE.parent / "sentinel" / "_key_table.py"

ASSIGN = re.compile(r'^[ \t]*([A-Z0-9_]+)[ \t]*=[ \t]*"([^"]*)"[ \t]*(?:#[^\n]*)?$',
                    re.M)
ARCH_MEMBER = re.compile(r'^[ \t]+([A-Z][A-Z0-9_]+)[ \t]*=[ \t]*auto\(\)', re.M)


def derive(text: str) -> dict:
    """All CONSTANT = "dotted.key" assignments in the vendored constants file."""
    found = {}
    for match in ASSIGN.finditer(text):
        const_name, pattern = match.group(1), match.group(2)
        if "." not in pattern:
            continue
        found[pattern] = const_name
    return found


def derive_archs(text: str) -> set:
    """MODEL_ARCH enum members (LLAMA, QWEN2, ...) -> official lowercase arch ids."""
    block = text.split("class MODEL_ARCH(IntEnum):", 1)
    if len(block) < 2:
        return set()
    body = block[1].split("\n\n", 1)[0]
    out = set()
    for match in ARCH_MEMBER.finditer(body):
        name = match.group(1)
        if name in ("MMPROJ",):  # dummy arch from clip.cpp, not a text model
            continue
        out.add(name.lower())
    return out


def render(keys: dict, archs: set, digest: str) -> str:
    body = repr(sorted(keys))
    arch_body = repr(sorted(archs))
    return ("# AUTO-GENERATED by tools/derive_keys.py -- DO NOT EDIT BY HAND.\n"
            "# Official GGUF metadata key patterns and arch ids, extracted from\n"
            "# upstream (ggml-org/llama.cpp master, gguf-py/gguf/constants.py).\n"
            "KEYS_DERIVED_FROM = 'ggml-org/llama.cpp master gguf-py/gguf/constants.py'\n"
            f"KEYS_VENDORED_SHA = {digest!r}\n"
            f"KEY_PATTERNS = {body}\n"
            f"ARCH_NAMES = {arch_body}\n")


def main() -> int:
    text = VENDOR.read_text()
    keys = derive(text)
    archs = derive_archs(text)
    digest = hashlib.sha256(VENDOR.read_bytes()).hexdigest()
    TARGET.write_text(render(keys, archs, digest[:16]))
    print("keys:", len(keys), "archs:", len(archs))
    probe = [k for k in keys if k.endswith(".tokens") or k.endswith(".architecture")]
    print("probe:", probe[:4])
    return 0


if __name__ == "__main__":
    sys.exit(main())
